### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ImagicalGamer** [ImagicalGamer/TrinketNew#1]
- [ ] Trinket Server (Probs Python or PHP)

- [ ] Full Packet System

- [ ] Error Management System

- [ ] Improve Security

**Comment by ImKyd** [comment]
Can you create tutorial how correct use it?

**Comment by ImagicalGamer** [comment]
It's moving to github.com/TransendStudios/TrinketPM, many more features are being added and yes I will create a tutorial
